---
name: Assignment
break: true
fastfail: false
indent: 4
version: v1.1.0
startup: poetry install
---

writing/reflection.md:
    --description "Complete all TODOs in writing/reflection.md" MatchFileFragment --fragment TODO --count 0 --exact


--description "Add --desc option" MatchCommandRegex --command "poetry run python sort.py --desc 23 4 15" --regex "\[0\] 23\n\[1\] 15\n\[2\] 4" --count 1 --exact
--description "Add --max option" MatchCommandRegex --command "poetry run python sort.py --max 15 23 4 15" --regex "\[0\] 4\n\[1\] 15" --count 1 --exact
--description "Implement ability to run --desc and --max together" MatchCommandRegex --command "poetry run python sort.py --desc --max 15 23 4 15" --regex "\[0\] 15\n\[1\] 4" --count 1 --exact
--description "Add specified help text for --desc option" MatchCommandFragment --command "poetry run python sort.py --help" --fragment "Sort numbers in descending order" --count 1 --exact
--description "Add specified help text for --max option" MatchCommandFragment --command "poetry run python sort.py --help" --fragment "Exclude any numbers above this number" --count 1 --exact